In [1]:
from numpy import array
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelBinarizer

In [2]:
data = ['Dog', 'Dog', 'Panda', 'Cat', 'Panda']
values = array(data)


In [3]:
values

array(['Dog', 'Dog', 'Panda', 'Cat', 'Panda'], dtype='<U5')

In [13]:
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print("Codificados em inteiros", integer_encoded)
print("As classes mantidas", label_encoder.classes_)

Codificados em inteiros [1 1 2 0 2]
As classes mantidas ['Cat' 'Dog' 'Panda']


In [25]:
onehot_encoder = OneHotEncoder(sparse = False)
ie = onehot_encoder.fit_transform(integer_encoded.reshape(len(integer_encoded), 1))
print("Codificados em inteiros", integer_encoded)
print("Redimensionado para duas dimensões 5 linnhas x 1 coluna \n", integer_encoded.reshape(len(integer_encoded), 1))
print('Rótulos com hot encoder\n', ie)
print(onehot_encoder.categories_)

Codificados em inteiros [1 1 2 0 2]
Redimensionado para duas dimensões 5 linnhas x 1 coluna 
 [[1]
 [1]
 [2]
 [0]
 [2]]
Rótulos com hot encoder
 [[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]
[array([0, 1, 2], dtype=int64)]


In [20]:
lb = LabelBinarizer()
lb_ie = lb.fit_transform(values)
print(lb_ie)
print('Classes', lb.classes_)

[[0 1 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]]
Classes ['Cat' 'Dog' 'Panda']


In [28]:
print(values)
onehot_encoder.fit_transform(values.reshape(len(integer_encoded), 1))

['Dog' 'Dog' 'Panda' 'Cat' 'Panda']


array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [27]:
print(onehot_encoder.categories_)

[array(['Cat', 'Dog', 'Panda'], dtype='<U5')]
