In [9]:
import tensorflow as tf

In [10]:
constant_0 = tf.constant([[1, 2], [3, 4]])
constant_1 = tf.constant([[-1, 3], [4, 2]])

In [11]:
result_multiplicate_0 = tf.matmul(constant_0, constant_1)
print(result_multiplicate_0)
type(result_multiplicate_0)

tf.Tensor(
[[ 7  7]
 [13 17]], shape=(2, 2), dtype=int32)


tensorflow.python.framework.ops.EagerTensor

In [12]:
result_multiplicate_1 = tf.matmul(constant_0, constant_1)
print(result_multiplicate_1)

tf.Tensor(
[[ 8 10]
 [10 16]], shape=(2, 2), dtype=int32)


In [13]:
constant_matrix_2 = tf.constant([[2, 3], [0, 1], [-1, 4]])
constant_matrix_3 = tf.constant([[1, 2, 3], [-2, 0 ,4]])
result_multiplicate_1 = tf.matmul(constant_matrix_2, constant_matrix_3)
print(result_multiplicate_1)

tf.Tensor(
[[-4  4 18]
 [-2  0  4]
 [-9 -2 13]], shape=(3, 3), dtype=int32)
