In [1]:
import tensorflow as tf

In [7]:
constant_a = tf.constant([9, 8, 7], name = 'a')
constant_b = tf.constant([1, 2, 3], name = 'b')
print(constant_a + constant_b)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [8]:
matrix_1 = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]], name = 'matrix_1')
print(matrix_1)
type(matrix_1)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


tensorflow.python.framework.ops.EagerTensor

In [10]:
matrix_2 = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]], name = 'matrix_1')
sum_1 = tf.add(matrix_1, matrix_2)
print(sum_1)

tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]], shape=(3, 3), dtype=int32)


In [11]:
matrix_3 = tf.constant([[1, 2, 3], [4, 5, 6]])
matrix_4 = tf.constant([[1], [2]])
matrix_result = tf.add(matrix_3, matrix_4)
print(matrix_result)

tf.Tensor(
[[2 3 4]
 [6 7 8]], shape=(2, 3), dtype=int32)
